services:
  - type: worker
    name: instagram-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false